### ISSUE TITLE
Doesn't work with NPP 64bit

### ISSUE THREAD

**Issue by TheIdanLapid** [geoffmcl/NppTidy2#3]
![image](https://user-images.githubusercontent.com/5512895/33713786-76bb2952-db01-11e7-8a6c-3dc57a8468af.png)
This is what I got when I opened NPP

**Comment by geoffmcl** [comment]
@enderGames thanks for the issue... I hope I can help...

First my install of NPP is a 32-bit version, so I only built a 32-bit tidy2.dll...

But if you have installed the 64-bit version of NPP, then for sure you will need to build the tidy2.dll likewise in 64-bits...

You do not mention what MSVC version you are using, if that is what you are using, and there are usually some **extra** steps to build the 64-bit version...

Seems normally cmake will default to using the 32-bit version if you just build using the simple commands shown in the `README.md`...

First you should be in a MSVC 64-bit command prompt... you may have a shortcut for this, or this can be done in a batch file, like `'call "C:\Program Files (x86)\Microsoft Visual Studio %VCVERS%.0\VC\vcvarsall.bat" AMD64'`... where VCVERS is the MSVC version...

Then you must tell cmake to generate the 64-bit build files... that is add `-G "Visual Studio %VCVERS% Win64"`... note the addition of **Win64** architecture  at the end...

This is all a bit complicated to explain in detail, but if you tell me more what you have done so far, maybe I can help with the additional steps required...

**Comment by geoffmcl** [comment]
@enderGames just tried a 64-bit build, and had to make a small **fix**

Also added a `build.x64` folder with a convenient `build-me.bat`... may need some small adjustments for your **VCVERS**, and where the latest **tidy** is installed...

Advise how you get on... thanks...

**Comment by TheIdanLapid** [comment]
@geoffmcl Thanks for your efforts! It works!
~ ***Bowing down*** ~

**Comment by geoffmcl** [comment]
@enderGames glad you got something working ;=))

You may have noted in issue #4 I have added some code the show the current versions, both of the `Tidy2.dll`, and the `libtidy` in use in the `About` dialog... see `set-vers` branch... and will try to get around to presenting some binary **releases**, if time permits...

Meantime, assume this can be closed... thanks...
