### ISSUE TITLE
Where is Tidy2.dll?

### ISSUE THREAD

**Issue by NocniHacker** [geoffmcl/NppTidy2#8]
I downloaded zip but there isn't Tidy2.dll for installation?

**Comment by geoffmcl** [comment]
@NocniHacker not sure which zip you downloaded...

From https://github.com/geoffmcl/NppTidy2/releases/tag/2.0.5 I just downloaded -

```
2019-01-06  14:13           154,390 Tidy2-2.0.5-vc140-md-64b.7z
```

And 7z shows me it contains `Tidy2.dll` -

```
C:\Users\user\Downloads>"C:\Program Files\7-Zip\7z.exe"  l Tidy2-2.0.5-vc140-md-64b.7z

7-Zip [64] 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Listing archive: Tidy2-2.0.5-vc140-md-64b.7z

--
Path = Tidy2-2.0.5-vc140-md-64b.7z
Type = 7z
Method = LZMA BCJ
Solid = -
Blocks = 1
Physical Size = 154390
Headers Size = 186

   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2017-12-19 01:38:03 ....A       742400       154204  Tidy2-2.0.5-vc140-md-64b\bin\Tidy2.dll
------------------- ----- ------------ ------------  ------------------------
                                742400       154204  1 files, 0 folders
```

What zip did you download? Do not understand... did I miss one... please explain... thanks

**Comment by NocniHacker** [comment]
I am bigger noob than I though. I clicked on green button, "Clone or Download". While we're here, how do I determine which version to download (my OS and N++ are 64bit):

- vc100-md
- vc140-md
or
- vc140-mt

**Comment by geoffmcl** [comment]
@NocniHacker, as the comments on that release page indicate...

It depends whether you have a version of MSVC installed, or at least the [Redistributables](https://www.microsoft.com/en-gb/download/details.aspx?id=48145) installed - then you may be able to use the appropriate  matching `-md-` version...

Otherwise choose an `-mt-` version... it only has a dependence on 4 system imports: `KERNEL32.dll SHELL32.dll SHLWAPI.dll USER32.dll`... which should always be present...

HTH...

**Comment by NocniHacker** [comment]
Thank you for your support, it works like a charm.
btw, what is difference between yours and this version https://github.com/bruderstein/NppTidy2 ?

**Comment by geoffmcl** [comment]
@NocniHacker glad you got something working ;=))

I do not remember the exact differences with `brunderstein` now... I note my fork `next` branch shows it is some 48 commits **ahead**... thus could review the changes... of course one thing was adding my name to the `About` dialog... but there were a few others...

Enjoy...
